version: "3.8"

services:
  backend:
    build:
      dockerfile: backend.Dockerfile
    ports:
      - "3000:3000"
  frontend:
    build:
      dockerfile: frontend.Dockerfile
    ports:
      - "3001:80"
    environment:
      - REACT_APP_GAME_SERVICE_API_HOST=http://localhost:3000
  test:
    build:
      dockerfile: tests.Dockerfile
